@baseUrl = http://localhost:3000

### SignUp (create user1)
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "login": "user1",
  "password": "pass1"
}

### SignUp (create user2)
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "login": "user2",
  "password": "pass2"
}

### SignIn user1 (Basic auth) -> accessTokenUser1
# base64("user1:pass1") = dXNlcjE6cGFzczE=
POST {{baseUrl}}/signin
Authorization: Basic dXNlcjE6cGFzczE=

### SignIn user2 (Basic auth) -> accessTokenUser2
# base64("user2:pass2") = dXNlcjI6cGFzczI=
POST {{baseUrl}}/signin
Authorization: Basic dXNlcjI6cGFzczI=

> {%
  client.global.set("accessTokenUser2", response.body.accessToken);
%}

