@baseUrl = http://localhost:3000

### Smoke: Unauthorized should be 401
GET {{baseUrl}}/games

### Smoke: Authorized GET /games (should return array)
GET {{baseUrl}}/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMmQ2Y2Q0MS1iYjNjLTQ0MDctYjZiNC1lOGFiYzhmODhlYjQiLCJpYXQiOjE3NzUyMTU0MDQsImV4cCI6MTc3NTIxNjMwNH0.in0SoneScSdZMCoLSIzJb57vHtdKMLdboiPZYQzedaY

