@baseUrl = http://localhost:3000
@accessTokenUser1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMmQ2Y2Q0MS1iYjNjLTQ0MDctYjZiNC1lOGFiYzhmODhlYjQiLCJpYXQiOjE3NzUyMTY0NDcsImV4cCI6MTc3NTIxNzM0N30.PQ-ft-6ObkJ3O4uihrpoBmX2T2tYrscKBwU5D02a4Co
@gameUuidPve = 8fd206f5-29f3-458e-afd6-ccdc2d3f9c93

### Create PvE game (vs computer)
POST {{baseUrl}}/games
Authorization: Bearer {{accessTokenUser1}}
Content-Type: application/json

{
  "opponent": "computer"
}

### Get game
GET {{baseUrl}}/games/{{gameUuidPve}}
Authorization: Bearer {{accessTokenUser1}}

### Make a move (row/col are 0..2)
POST {{baseUrl}}/games/{{gameUuidPve}}/move
Authorization: Bearer {{accessTokenUser1}}
Content-Type: application/json

{
  "row": 1,
  "col": 0
}

### Make another move
POST {{baseUrl}}/games/{{gameUuidPve}}/move
Authorization: Bearer {{accessTokenUser1}}
Content-Type: application/json

{
  "row": 1,
  "col": 1
}

### Legacy endpoint alias (same as /games/:uuid/move)
POST {{baseUrl}}/game/{{gameUuidPve}}/move
Authorization: Bearer {{accessTokenUser1}}
Content-Type: application/json

{
  "row": 2,
  "col": 2
}

