@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlOTgyNjktNmU5OS00NTBhLTlmOTktZTI3YzIxNzk5MDZiIiwibG9naW4iOiJqa3MiLCJpYXQiOjE3NzU4MjY4MTQsImV4cCI6MTc3NTgyNjkzNH0.ktW0CsiJjKQDbS2Cfn2yg1sAhARBj3MBNeSPSJxIS7M

@userUuid = ca49baae-47c2-4abe-a8ba-4465d05e9aa0

GET http://localhost:3000/user/{{userUuid}}
Authorization: Bearer {{access_token}}