@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlOTgyNjktNmU5OS00NTBhLTlmOTktZTI3YzIxNzk5MDZiIiwibG9naW4iOiJqa3MiLCJpYXQiOjE3NzU2NTc4NjAsImV4cCI6MTc3NTY1ODc2MH0.6Das6tt08WTJmIchOQo5JXKcE8RTQ5u6RPMXuD3Dzw0

@userUuid = ca49baae-47c2-4abe-a8ba-4465d05e9aa0

GET http://localhost:3000/user/{{userUuid}}
Authorization: Bearer {{access_token}}