// game/errors/game.error-codes.enum.ts
export enum GameErrorCode {
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  // GAME_DOMAIN_CONVERT_FAILED = 'GAME_DOMAIN_CONVERT_FAILED',
  GAME_NOT_YOUR_TURN = 'GAME_NOT_YOUR_TURN',
  GAME_INVALID_MOVE = 'GAME_INVALID_MOVE',
  GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
  GAME_PLAYER_NOT_FOUND = 'GAME_PLAYER_NOT_FOUND',
  GAME_MISSING_PLAYER_X = 'GAME_MISSING_PLAYER_X',
  GAME_MISSING_PLAYER_O = 'GAME_MISSING_PLAYER_O',
}
