@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlOTgyNjktNmU5OS00NTBhLTlmOTktZTI3YzIxNzk5MDZiIiwibG9naW4iOiJqa3MiLCJpYXQiOjE3NzU4MjY4MTQsImV4cCI6MTc3NTgyNjkzNH0.ktW0CsiJjKQDbS2Cfn2yg1sAhARBj3MBNeSPSJxIS7M

POST http://localhost:3000/game/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "opponent": "player",
  "board": [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ]
}