@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlOTgyNjktNmU5OS00NTBhLTlmOTktZTI3YzIxNzk5MDZiIiwibG9naW4iOiJqa3MiLCJpYXQiOjE3NzU2NDY3ODYsImV4cCI6MTc3NTY0NzY4Nn0.5e1HliJcVaYpgYlrCMCReQci5NlNOXLnTBe4mUKq-hk
@gameUuid = bc47245d-894a-4150-baed-87e9e6a53d6f
@playerUuid = 5fe98269-6e99-450a-9f99-e27c2179906b


POST http://localhost:3000/game/{{gameUuid}}/{{playerUuid}}/move/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "newBoard": [
    [1, 1, 2],
    [1, 2, 0],
    [2, 0, 0]
  ]
}