@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiY2E0OWJhYWUtNDdjMi00YWJlLWE4YmEtNDQ2NWQwNWU5YWEwIiwibG9naW4iOiJ0dXJuZXJrbyIsImlhdCI6MTc3NTY1MzEwNSwiZXhwIjoxNzc1NjU0MDA1fQ.iqkWn2QHYad-WsINNwgYwZ193JK7kFF3WyKLYKXvYiU
@gameUuid = 17c66769-328d-4976-ba4c-37f676442f71


POST http://localhost:3000/game/{{gameUuid}}/move/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "newBoard": [
    [1, 2, 0],
    [1, 2, 0],
    [1, 2, 0]
  ]
}