@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNWZlOTgyNjktNmU5OS00NTBhLTlmOTktZTI3YzIxNzk5MDZiIiwibG9naW4iOiJqa3MiLCJpYXQiOjE3NzU2NDkzOTQsImV4cCI6MTc3NTY1MDI5NH0.VwnDHAfAmAGA47UZuy6R97sKpd7f2dCOhxUqZ758fcE
@playerUuid = 5fe98269-6e99-450a-9f99-e27c2179906b

POST http://localhost:3000/game/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "playerUuid": "{{playerUuid}}",
  "opponent": "player",
  "board": [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ]
}