@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiY2E0OWJhYWUtNDdjMi00YWJlLWE4YmEtNDQ2NWQwNWU5YWEwIiwibG9naW4iOiJ0dXJuZXJrbyIsImlhdCI6MTc3NTgyNzYwOCwiZXhwIjoxNzc1ODI4ODA4fQ.bA4yH9pg2epx6Rhi7DSkO_dXDHWhJLYv2Bfh0xD9eGo
@gameUuid = e2d7095c-c03f-4bcf-90b5-20b61d43fd65


POST http://localhost:3000/game/{{gameUuid}}/join/
Authorization: Bearer {{access_token}}