GET http://localhost:3000/api/game/84da5501-b01b-409e-806f-861fc986471a/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Mjg3NDEzOC02YjNmLTRlYzEtYjAxZS00MzdkZjY3MGE0YjMiLCJpYXQiOjE3NzE5MzI5ODksImV4cCI6MTc3MjAxOTM4OX0.zijwRQ3CnIKl9hvDMPbgZ_7OotqT0Ll3Hkj4Q3tEHPk