#POST http://localhost:3000/api/game/bbb
#Content-Type: application/json
#
#{
#  "board": [
#    [2, 1, 2],
#    [1, 0, 0],
#    [2, 1, 1]
#  ]
#}

#POST http://localhost:3000/api/auth/signup
#Content-Type: application/json
#
#{
#  "login": "jsk101dev",
#  "password": "9140656@Kj"
#}


#POST http://localhost:3000/api/auth/login
#Authorization: Basic anNrMTAxZGV2OjkxNDA2NTZAS2o=


POST http://localhost:3000/api/game
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YzgxZjE2Yy1iYWQ1LTRmOTQtODJiNy03YTg5ZDZhNTljYWUiLCJpYXQiOjE3NzE2Njk5NjQsImV4cCI6MTc3MTc1NjM2NH0.G4bYFOJ3wfjr2zQF0Qr6faNI_Vgq1Gc5x-X1pYZslO0
Content-Type: application/json

{
  "mode": "USER",
  "board": [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ]
}
