#POST http://localhost:3000/api/game/bbb
#Content-Type: application/json
#
#{
#  "board": [
#    [2, 1, 2],
#    [1, 0, 0],
#    [2, 1, 1]
#  ]
#}

#POST http://localhost:3000/api/auth/signup
#Content-Type: application/json
#
#{
#  "login": "jsk101dev",
#  "password": "91@Kj"
#}

#POST http://localhost:3000/api/auth/login
#Authorization: Basic amtzMjAyZGV2OjkxNDA2NTZAS2o=

GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OWNlZmRmNy1lNzU2LTQ4MTUtOWJlNy0xZjY4NTVjNDdkODMiLCJsb2dpbiI6ImprczIwMmRldiIsImlhdCI6MTc3MTU4OTM2NSwiZXhwIjoxNzcxNjc1NzY1fQ.ACfngjbsxYX3iQNkbU8vx6kO72jqIVpGlhxYB7x1-gk