POST http://localhost:3000/api/game/976875cd-a024-420d-83ae-f57c03874f3c/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Mjg3NDEzOC02YjNmLTRlYzEtYjAxZS00MzdkZjY3MGE0YjMiLCJpYXQiOjE3NzE3MzM2ODgsImV4cCI6MTc3MTgyMDA4OH0.8Ql0yO-YP-t77QLU4ACubDh-gES0n59aNLaelJud4ZE
