POST http://localhost:3000/api/game/fb0a79b9-0854-4d77-8f01-1dd2151eec69/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1M2Q5YzgyZC0zNDQyLTQ2OGUtODI5Ni1jYTBkNmUzZTM1ZGMiLCJpYXQiOjE3NzE4NDM4MTUsImV4cCI6MTc3MTkzMDIxNX0.3Sojd8aGMQUWHYC9zeStzcOdGcTYtwIxCP7J2EMN5Bs
Content-Type: application/json

{
  "mode": "USER",
  "board": [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ]
}