POST http://localhost:3000/api/game/321fc94e-856c-400f-b3a9-355edb40b54b/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Mjg3NDEzOC02YjNmLTRlYzEtYjAxZS00MzdkZjY3MGE0YjMiLCJpYXQiOjE3NzE5MzM4MzgsImV4cCI6MTc3MjAyMDIzOH0.va-1cIAPtUGQ3iUJtmNz3r4xoJjo2CmMh_CTjuWp1KQ
Content-Type: application/json

{
  "mode": "USER",
  "board": [
    [0, 0, 2],
    [0, 1, 0],
    [0, 2, 0]
  ]
}