POST http://localhost:3000/api/game
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1M2Q5YzgyZC0zNDQyLTQ2OGUtODI5Ni1jYTBkNmUzZTM1ZGMiLCJpYXQiOjE3NzE5MzI3NDgsImV4cCI6MTc3MjAxOTE0OH0.gLVkGIHDxPus8m7Xcw1mxMLm1OZMAwAX9z_ZGWnOMN8
Content-Type: application/json

{
  "mode": "USER",
  "board": [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ]
}